fix ci

diff --git a/tests/4space/Makefile b/tests/4space/Makefile
--- a/tests/4space/Makefile
+++ b/tests/4space/Makefile
@@ -1,4 +1,4 @@
-SHELL := /bin/bash
+SHELL := bash
 
 
 .PHONY: start
@@ -16,28 +16,23 @@ stop: # stop app
 .PHONY: loading
 loading: # show loading state
 	set -e; \
-	if [[ $${@} == '--fin' ]]; \
-	then \
-		echo "loading finished"; \
-	else \
-		echo "loading started"; \
-	fi; \
+	echo "loading" $${@}; \
 
 .PHONY: build
 build: lint # build app for environment [vars: env]
 	set -e; \
-	[[ -n `printf '%s' '$(env)'` ]] && echo "buiding app for `printf '%s' '$(env)'`" || echo "error: missing env"; \
+	[ "`printf '%s' '$(env)'`" != "" ] && echo "buiding app for `printf '%s' '$(env)'`" || echo "error: missing env"; \
 
 .PHONY: test
 test: # run all tests or specific tests [vars: name1, name2, etc.]
 	set -e; \
 	run build env=test; \
-	[[ -n $${@} ]] && echo "running tests $${@}" || echo "running all tests"; \
+	[ "$${@}" != "" ] && echo "running tests $${@}" || echo "running all tests"; \
 
 .PHONY: lint
 lint: # lint all files or specific file [vars: file]
 	set -e; \
-	[[ -n $${1} ]] && echo "linting file $${1}" || echo "linting all files"; \
+	[ "$${1}" != "" ] && echo "linting file $${1}" || echo "linting all files"; \
 
 .PHONY: complex
 complex: # a sample command exploring complex multiline syntax
diff --git a/tests/compact/Makefile b/tests/compact/Makefile
--- a/tests/compact/Makefile
+++ b/tests/compact/Makefile
@@ -1,4 +1,4 @@
-SHELL := /bin/bash
+SHELL := bash
 
 
 .PHONY: start
@@ -16,28 +16,23 @@ stop: # stop app
 .PHONY: loading
 loading: # show loading state
 	set -e; \
-	if [[ $${@} == '--fin' ]]; \
-	then \
-		echo "loading finished"; \
-	else \
-		echo "loading started"; \
-	fi; \
+	echo "loading" $${@}; \
 
 .PHONY: build
 build: lint # build app for environment [vars: env]
 	set -e; \
-	[[ -n `printf '%s' '$(env)'` ]] && echo "buiding app for `printf '%s' '$(env)'`" || echo "error: missing env"; \
+	[ "`printf '%s' '$(env)'`" != "" ] && echo "buiding app for `printf '%s' '$(env)'`" || echo "error: missing env"; \
 
 .PHONY: test
 test: # run all tests or specific tests [vars: name1, name2, etc.]
 	set -e; \
 	run build env=test; \
-	[[ -n $${@} ]] && echo "running tests $${@}" || echo "running all tests"; \
+	[ "$${@}" != "" ] && echo "running tests $${@}" || echo "running all tests"; \
 
 .PHONY: lint
 lint: # lint all files or specific file [vars: file]
 	set -e; \
-	[[ -n $${1} ]] && echo "linting file $${1}" || echo "linting all files"; \
+	[ "$${1}" != "" ] && echo "linting file $${1}" || echo "linting all files"; \
 
 .PHONY: complex
 complex: # a sample command exploring complex multiline syntax
@@ -45,11 +40,11 @@ complex: # a sample command exploring complex multiline syntax
 	echo "--- for loops ---"; \
 	for x in abc hjkl xyz; \
 	do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done; \
 	echo; \
 	for x in abc hjkl xyz; do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done; \
 	echo; \
 	for x in abc hjkl xyz; \
@@ -59,11 +54,11 @@ complex: # a sample command exploring complex multiline syntax
 	echo "--- while loops ---"; \
 	while read x; \
 	do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done <<< $$'abc\n hjkl\n xyz'; \
 	echo; \
 	while read x; do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done <<< $$'abc\n hjkl\n xyz'; \
 	echo; \
 	while read x; \
@@ -74,26 +69,26 @@ complex: # a sample command exploring complex multiline syntax
 	x=''; \
 	if [[ -z "$${x}" ]]; \
 	then \
-		echo -n " abc"; \
-		echo -n " ::"; \
+	echo -n " abc"; \
+	echo -n " ::"; \
 	elif [[ "$${x}" =~ a[Bb][a-z]$$ ]]; \
 	then \
-		echo -n " hjkl"; \
-		echo -n " ::"; \
+	echo -n " hjkl"; \
+	echo -n " ::"; \
 	else \
-		echo -n " xyz"; \
-		echo -n " ::"; \
+	echo -n " xyz"; \
+	echo -n " ::"; \
 	fi; \
 	y=''; \
 	if [[ -n "$${y}" ]]; then \
-		echo -n " abc"; \
-		echo -n " ::"; \
+	echo -n " abc"; \
+	echo -n " ::"; \
 	elif ! [[ "$${y}" =~ a[Bb][a-z]$$ ]]; then \
-		echo -n " hjkl"; \
-		echo -n " ::"; \
+	echo -n " hjkl"; \
+	echo -n " ::"; \
 	else \
-		echo -n " xyz"; \
-		echo -n "  ::"; \
+	echo -n " xyz"; \
+	echo -n "  ::"; \
 	fi; \
 	z=''; \
 	if [[ -z "$${x}" ]]; \
@@ -106,11 +101,11 @@ complex: # a sample command exploring complex multiline syntax
 	echo "--- for loops :: pathological semicolon usage ---"; \
 	for x in abc hjkl xyz; \
 	do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done; \
 	echo; \
 	for x in abc hjkl xyz; do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done; \
 	echo; \
 	for x in abc hjkl xyz; \
@@ -120,11 +115,11 @@ complex: # a sample command exploring complex multiline syntax
 	echo "--- while loops :: pathological semicolon usage ---"; \
 	while read x; \
 	do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done <<< $$'abc\n hjkl\n xyz'; \
 	echo; \
 	while read x; do \
-		echo -n " $${x} ::"; \
+	echo -n " $${x} ::"; \
 	done <<< $$'abc\n hjkl\n xyz'; \
 	echo; \
 	while read x; \
@@ -135,26 +130,26 @@ complex: # a sample command exploring complex multiline syntax
 	x=''; \
 	if [[ -z "$${x}" ]]; \
 	then \
-		echo -n " abc"; \
-		echo -n " ::"; \
+	echo -n " abc"; \
+	echo -n " ::"; \
 	elif [[ "$${x}" =~ a[Bb][a-z]$$ ]]; \
 	then \
-		echo -n " hjkl"; \
-		echo -n " ::"; \
+	echo -n " hjkl"; \
+	echo -n " ::"; \
 	else \
-		echo -n " xyz"; \
-		echo -n " ::"; \
+	echo -n " xyz"; \
+	echo -n " ::"; \
 	fi; \
 	y=''; \
 	if [[ -n "$${y}" ]]; then \
-		echo -n " abc"; \
-		echo -n " ::"; \
+	echo -n " abc"; \
+	echo -n " ::"; \
 	elif ! [[ "$${y}" =~ a[Bb][a-z]$$ ]]; then \
-		echo -n " hjkl"; \
-		echo -n " ::"; \
+	echo -n " hjkl"; \
+	echo -n " ::"; \
 	else \
-		echo -n " xyz"; \
-		echo -n " ::"; \
+	echo -n " xyz"; \
+	echo -n " ::"; \
 	fi; \
 	z=''; \
 	if [[ -z "$${x}" ]]; \
diff --git a/tests/nodesc/Runfile b/tests/nodesc/Runfile
--- a/tests/nodesc/Runfile
+++ b/tests/nodesc/Runfile
@@ -8,19 +8,14 @@ stop:
 HUP run loading --fin
 echo "stopping app"
 loading:
-if [[ $(@) == '--fin' ]]
-then
-  echo "loading finished"
-else
-  echo "loading started"
-fi
+echo "loading" $(@)
 build:lint
-[[ -n $(env) ]] && echo "buiding app for $(env)" || echo "error: missing env"
+[ "$(env)" != "" ] && echo "buiding app for $(env)" || echo "error: missing env"
 test:
 run build env=test
-[[ -n $(@) ]] && echo "running tests $(@)" || echo "running all tests"
+[ "$(@)" != "" ] && echo "running tests $(@)" || echo "running all tests"
 lint:
-[[ -n $(1) ]] && echo "linting file $(1)" || echo "linting all files"
+[ "$(1)" != "" ] && echo "linting file $(1)" || echo "linting all files"
 complex:
 echo "--- for loops ---"
 for x in abc hjkl xyz
diff --git a/tests/tabbed/Runfile b/tests/tabbed/Runfile
--- a/tests/tabbed/Runfile
+++ b/tests/tabbed/Runfile
@@ -12,22 +12,17 @@ stop: # stop app
 	echo "stopping app"
 
 loading: # show loading state
-	if [[ $(@) == '--fin' ]]
-	then
-		echo "loading finished"
-	else
-		echo "loading started"
-	fi
+	echo "loading" $(@)
 
 build: lint # build app for environment [vars: env]
-	[[ -n $(env) ]] && echo "buiding app for $(env)" || echo "error: missing env"
+	[ "$(env)" != "" ] && echo "buiding app for $(env)" || echo "error: missing env"
 
 test: # run all tests or specific tests [vars: name1, name2, etc.]
 	run build env=test
-	[[ -n $(@) ]] && echo "running tests $(@)" || echo "running all tests"
+	[ "$(@)" != "" ] && echo "running tests $(@)" || echo "running all tests"
 
 lint: # lint all files or specific file [vars: file]
-	[[ -n $(1) ]] && echo "linting file $(1)" || echo "linting all files"
+	[ "$(1)" != "" ] && echo "linting file $(1)" || echo "linting all files"
 
 complex: # a sample command exploring complex multiline syntax
 	echo "--- for loops ---"
